# Generated by Django 3.0.5 on 2021-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210602_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(db_table='api_genre_title', to='api.Genre', verbose_name='Жанры произведения'),
        ),
    ]
