# Generated by Django 3.0.5 on 2021-06-02 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание произведения'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('title_id', models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, to='api.Title')),
            ],
        ),
    ]
